name: ğŸ§ª Run Spring Boot Tests on Pull Request

on:
  pull_request:
    branch: [ main, dev ]

jobs:
  project-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ–¼ï¸ Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: ğŸ—ï¸ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸŸï¸ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ§ª Spring Boot Test
        run: ./gradlew clean test